---
- name: display filesystem usage
  hosts: all
  gather_facts: False
  tasks:
    - name: retrieve filesystem usage
      command:
        argv:
          - /usr/bin/df
          - '-h'
      register: usage

    - name: display filesystem usage
      debug:
        msg: "{{ usage.stdout_lines }}"
